image: debian:12

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DEBIAN_FRONTEND: 'noninteractive'
  SCALENODE_CPU: 2

.install_deps: &install_deps |-
  apt-get -qqy update
  apt-get -qqy --no-install-recommends install ca-certificates python3 python3-pip git
  rm /usr/lib/python3.11/EXTERNALLY-MANAGED

basic_test:
  script:
    - *install_deps
    - pip3 install .
    - tests/basic_test.sh
  artifacts:
    when: always
    paths:
      - build
