image: debian:12

include: testplanner-ci-scripts@main:testplanner.yml

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DEBIAN_FRONTEND: 'noninteractive'
  SCALENODE_CPU: 2

before_get_sources:
  - apt-get -qqy update
  - apt-get -qqy --no-install-recommends install ca-certificates python3 python3-pip python3-venv git wget curl
  - apt-get -qqy --no-install-recommends install help2man libfl-dev make g++ git bison flex gperf libreadline-dev libbz2-dev autoconf python3-sphinx python3-docopt
  - apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl
  - rm /usr/lib/python3.11/EXTERNALLY-MANAGED

lint:
  script:
    - pip3 install ruff pre-commit
    - pre-commit run --all-files || (echo "pre-commit changes:" && git diff && false)

basic_test:
  script:
    - pip3 install .
    - tests/basic_test.sh
  artifacts:
    when: always
    paths:
      - build

i3c_docs_build:
  script:
    - git clone https://github.com/verilator/verilator -b v5.024
    - pushd verilator
    -   autoconf
    -   ./configure
    -   make -j$(nproc)
    -   make install
    -   verilator --version
    - popd
    - git clone --recursive https://github.com/chipsalliance/i3c-core
    - pushd i3c-core
    -   ./install.sh
    -   export I3C_ROOT_DIR="`pwd`"
    -   export CALIPTRA_ROOT="${I3C_ROOT_DIR}/third_party/caliptra-rtl"
    -   make install-uvm
    -   source activate.sh
    -   make tests-axi
    -   pip3 install -r requirements.txt
    -   pip3 install -r doc/requirements.txt
    -   pip3 uninstall -y testplanner
    - popd
    - pip3 install -e .
    - pushd i3c-core
    -   REPO_URL="https://github.com/chipsalliance/i3c-core/tree/main/" make verification-docs-with-sim
    -   pushd doc
    -     TZ=UTC make html
    -   popd
    -   ls -lah doc/build
    - popd
  artifacts:
    when: always
    paths:
      - i3c-core/doc/build
      - i3c-core/verification/cocotb
